# Generated by Django 3.0.5 on 2020-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='bgimage',
            field=models.ImageField(default='', upload_to='shop/images/banner/bg'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images/banner/img'),
        ),
    ]
