# Generated by Django 3.0.5 on 2020-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200430_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=50)),
                ('order_name', models.CharField(max_length=50)),
                ('update_desc', models.CharField(max_length=50)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
